# Generated by Django 5.1 on 2024-09-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_reservation_guest_alter_reservation_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='hall',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
